import { Inter ,Montserrat} from "next/font/google";
import "./globals.css";

import Navbar from "./component/navbar/Navbar";
import Footer from "./component/footer/Footer";
import Analytics from "./component/analytics/Analitics.js";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Analytics/>
      <body className={montserrat.className}>
        <div className="container">
        <Navbar/>
        {children}


        <Footer/>
        </div>
          
        </body>
    </html>
  );
}
